spring:
  application:
    name: manager-web
  resources:
    static-locations: classpath:/static/, classpath:/templates/
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /
      suffix: .html
  ####整合数据库层
  datasource:
    name: test
    url: jdbc:mysql://192.168.80.101:3306/nc2017
    username: root
    password: 123456
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
